<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1750874890" />
    <testcase name="test_fifo_basic_operations" classname="test_fifo" file="/home/imp/work/uart/test/test_fifo.py" lineno="14" time="0.002592802047729492" sim_time_ns="30.001" ratio_time="11570.879476229886">
      <failure message="Test failed with RANDOM_SEED=1750874890" />
    </testcase>
    <testcase name="test_fifo_full_condition" classname="test_fifo" file="/home/imp/work/uart/test/test_fifo.py" lineno="46" time="0.0030298233032226562" sim_time_ns="190.001" ratio_time="62710.25765690904">
      <failure message="Test failed with RANDOM_SEED=1750874890" />
    </testcase>
    <testcase name="test_fifo_simultaneous_read_write" classname="test_fifo" file="/home/imp/work/uart/test/test_fifo.py" lineno="74" time="0.0017993450164794922" sim_time_ns="120.00099999999998" ratio_time="66691.48990380282">
      <failure message="Test failed with RANDOM_SEED=1750874890" />
    </testcase>
    <testcase name="test_fifo_random_operations" classname="test_fifo" file="/home/imp/work/uart/test/test_fifo.py" lineno="106" time="0.0009162425994873047" sim_time_ns="40.00100000000003" ratio_time="43657.651393182445">
      <failure message="Test failed with RANDOM_SEED=1750874890" />
    </testcase>
    <testcase name="test_fifo_reset_behavior" classname="test_fifo" file="/home/imp/work/uart/test/test_fifo.py" lineno="144" time="0.0010540485382080078" sim_time_ns="60.000999999999976" ratio_time="56924.323524994325">
      <failure message="Test failed with RANDOM_SEED=1750874890" />
    </testcase>
  </testsuite>
</testsuites>
